export const projectsList = [
  {
    id: "projects",
    title: "Sbored",
    description: `Sbored is a random activity generator. It allows users to choose
    from over 400,000 activities. Sbored went mini-viral on Twitter,
    receiving over 40,000 unique visitors in the first month. It ranked
    #7 on Product Hunt's Product of the Day, with 264 upvotes.`,
    imgUrl: "/sbored.png",
    url: `https://sbored.co`,
    order: "",
    techStack: ["Svelte", "Sveltekit", "Tailwind CSS", "Supabase"],
    gradientColor: "from-red-400 to-orange-400",
    shadowColor: "shadow-red-300",
    imageFade: "md:animate-fade-right",
    textFade: "md:animate-fade-left",
  },
  {
    id: "",
    title: "Millionaire Trivia",
    description: `Engage in an immersive trivia experience, showcasing your knowledge across various categories sourced from the Open Trivia DB. Challenge yourself and showcase your prowess in this personal showcase of trivia mastery. Can you get to $1 Million?`,
    imgUrl: "/trivia.png",
    url: `https://millionaire-trivia.vercel.app`,
    order: "md:order-2",
    techStack: ["React", "Next.JS", "Tailwind CSS"],
    gradientColor: "from-red-500 to-purple-400",
    shadowColor: "shadow-blue-300",
    imageFade: "md:animate-fade-left",
    textFade: "md:animate-fade-right",
  },
  {
    id: "",
    title: "Stimer",
    description: `Stimer is a simple time tracking tool built to improve productivity. In a world full of complex time management tools, Stimer aims to be a simple to use solution that can bring about big results. Note*: username = user, password = good3478`,
    imgUrl: "/stimer.png",
    url: `https://stimer-v2.vercel.app`,
    order: "",
    techStack: ["Svelte", "Sveltekit", "Tailwind CSS", "Supabase"],
    gradientColor: "from-indigo-500 via-purple-500 to-pink-500",
    shadowColor: "shadow-indigo-300",
    imageFade: "md:animate-fade-right",
    textFade: "md:animate-fade-left",
  },
];
